name: firebase_flutter_project
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  flutter_svg: ^1.0.3
  google_sign_in: ^5.2.4
  flutter_secure_storage: ^5.0.2
  otp_text_field: ^1.1.2
  cloud_firestore: ^3.1.10
  image_picker: ^0.8.4+11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/

